export const tips: Record<string, string> = {
  bounty: 'This program pays monetary rewards for valid reports',
  swag: 'This program offers merchandise or branded items as rewards',
  recognition: 'This program offers public credit, such as a hall of fame listing',
  safeHarborFull: 'Full legal protection for good-faith security researchers',
  safeHarborPartial: 'Some legal protection for researchers, with conditions',
  responseTime: 'Average time to receive a first response after submitting a report',
  bountyTime: 'Average time from report submission to bounty payout',
  resolutionTime: 'Average time from report submission to the issue being fixed',
  responseEfficiency: 'Overall responsiveness score based on triage and resolution speed',
  managed: 'Program is operated through a third-party bug bounty platform',
  confidentiality: 'Whether program details and reports are public or private',
  allowsDisclosure: 'Whether researchers may publish findings after resolution',
  pgpKey: 'PGP encryption key for sending sensitive report details securely',
  securityTxt: 'A standardized file that lists security contact information',
  preferredLanguages: 'Languages the security team prefers for report submissions',
  hiring: 'This company is actively hiring security researchers',
  payout: 'The bounty payout range for valid vulnerability reports',
  statPrograms: 'Total number of bug bounty and disclosure programs listed',
  statBounties: 'Programs that offer monetary rewards',
  statSafeHarbor: 'Programs with legal protections for good-faith researchers',
};
