name: 🐞 Insert Bounty List

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["📡 Populate Bounties"]
    types: [completed]
  push:
    branches: [ main ]
    paths: ['platform-programs.yml', 'independent-programs.yml']

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v5

      # Get current date-time (used for commit message)
      - name: Get Date 📅
        id: date
        run: echo "date=$(date +'%d-%b-%Y')" >> "$GITHUB_OUTPUT"

      # Downloads + installs Python (used for running gen scripts)
      - name: Set up Python 🐍
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      # Install contents of requirements.txt
      - name: Install dependencies 📥
        run: |
          python -m pip install --upgrade pip
          cd lib && pip install -r requirements.txt

      # The make command triggers all the Python scripts, generates output
      - name: Run make command 🔨
        run: python lib/insert-bounties.py

      # Commit and push the outputed JSON files
      - name: Commit and push generated files ⤴️
        run: |
          git config --global user.name "Liss-Bot"
          git config --global user.email "alicia-gh-bot@mail.as93.net"
          git add .github/README.md
          if git diff --staged --quiet; then
            echo "Nothin new added, so nothing to commit, exiting..."
          else
            git commit -m "Updates readme (auto-generated, on ${{ steps.date.outputs.date }})"
            git push
          fi
